### ISSUE TITLE
Uncaught TypeError: Cannot read property 'cursors' of undefined

### ISSUE THREAD

**Issue by ihaiker** [burodepeper/language-markdown#57] opened 2015-12-14 09:54 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.1
**System**: Mac OS X 10.10.5
**Thrown From**: [language-markdown](https://github.com/burodepeper/language-markdown) package, v0.7.0

### Stack Trace

Uncaught TypeError: Cannot read property 'cursors' of undefined

```
At /Users/haiker/.atom/packages/language-markdown/lib/main.coffee:162

TypeError: Cannot read property 'cursors' of undefined
    at Object.module.exports.getEditorAndPosition (/Users/haiker/.atom/packages/language-markdown/lib/main.coffee:162:22)
    at Object.module.exports.toggleTask (/Users/haiker/.atom/packages/language-markdown/lib/main.coffee:177:27)
    at atom-workspace.subscriptions.add.atom.commands.add.markdown:toggle-task (/Users/haiker/.atom/packages/language-markdown/lib/main.coffee:38:96)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:40.7.0 application:add-project-folder (atom-pane.pane.active)
  2x -0:03.7.0 markdown:toggle-task (input.hidden-input)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "projectHome": "/Users/haiker/",
    "openEmptyEditorOnStart": false,
    "disabledPackages": [
      "language-gfm",
      "language-gfm"
    ]
  }
}
```

### Installed Packages

```coffee
# User
language-gradle, v0.0.3
language-markdown, v0.7.0
language-sql, v0.20.0
markdown-preview-plus, v2.2.2

# Dev
No dev packages
```

**Comment by burodepeper** [comment] 2015-12-14 10:07
Hi @ihaiker,

Also considering the other issue you've reported, #56, have you tried restarting Atom? If so, does that still trigger both of these issues?

For this issue in particular, were you trying to toggle a task-list-item? Or did it occur on startup?

**Comment by burodepeper** [comment] 2015-12-14 10:17
I was able to replicate the issue by trying to toggle a task-list-item without having an editor selected, and I've published a patch (v0.7.1) that should fix this issue. Could you let me know if this works for you?

**Comment by burodepeper** [comment] 2015-12-22 10:57
@ihaiker Can you confirm if this bug is fixed for you?

**Comment by burodepeper** [comment] 2016-01-16 09:23
Closing this because the variation that I've been able to reproduce has been fixed.

**Closed by burodepeper** 2016-01-16 09:23 UTC
Labels: needs verification
