### ISSUE TITLE
Autocompletion does not seem to be working

### ISSUE THREAD

**Issue by githubnemo** [burodepeper/language-markdown#150] opened 2016-10-30 23:41 UTC
With `language-gfm` autocompletion works fine, with `language-markdown` it does not. It only works for things that are tagged with `gfm`, for example `gfm variable` nodes. Setting the file type to Github Markdown and then setting it back to Markdown makes it possible to use autocompleted words that exist in the buffer but not for words that are added afterwards.

Did I do something wrong or is this related to the reason why spell-checking does not work out of the box?

Atom 1.11.2, language-markdown 0.17.0

**Comment by burodepeper** [comment] 2016-10-31 08:16
Have you changed any of the settings of the `autocomplete-plus` package? As far as I know, a grammar package doesn't directly change any autocomplete behavior since that's what the other package is for. From the default settings, it seems that documents using the `.source.gfm` (used by `language-gfm`) scope aren't indexed for autocompletion, so it's weird that it seems to work for you when you've turned on `language-gfm`.

On another note, could you describe to me the autocompletion behavior you are expecting? Do you want words from the current document to show up as autocompletion options, or do you want words from any open documents to show up? The settings for `autocomplete-plus` are a bit misleading about that.

**Comment by githubnemo** [comment] 2016-10-31 14:39
> Have you changed any of the settings of the autocomplete-plus package?

I tried removing `.source.gfm` from the blacklist and probably permuted a fair bit of options (semi-randomly) to no avail. There is no file blacklist for `.md` files installed. The autocomplete-plus section of my `config.cson` says:

```
  "autocomplete-plus":
    confirmCompletion: "tab"
    suggestionListFollows: "Cursor"
```

> Do you want words from the current document to show up as autocompletion options, or do you want words from any open documents to show up? The settings for autocomplete-plus are a bit misleading about that.

I want both but the issue is that words from the *current* document are not completed, e.g. I type 'happywombat' in my document, skip two lines, type 'happy', press `ctrl+space` and nothing happens. No suggestion while typing either. `ctrl+space` is only bound to auto completion (checked with `ctrl+.`)

**Comment by burodepeper** [comment] 2016-10-31 14:42
Thanks for the additional information. I'll have a look if there's a difference between this package and `language-gfm`. If there is, I suppose it should be an "easy" fix. If there isn't, there's a good chance it's an issue with `autocomplete-plus`. Either way, I'll get back to you when I know more.

**Comment by githubnemo** [comment] 2016-10-31 14:47
Thanks. One more thing, I just found out that changing the default provider from Symbol to Fuzzy fixes the issue. That would make sense if it expects a grammar to provide symbols/classes for the words but does not know how to access the grammar of `language-markdown`.

**Comment by githubnemo** [comment] 2016-10-31 14:58
Yeah that was the issue. Adding 

```
'.text.md':
    autocomplete:
        symbols:
            constant:
                selector: "*"
                typePriority: 1
```

to `config/markdown.cson` fixed autocompletion. Everything is classified as constant then. I am not sure if it would make sense to have multiple classes for markdown documents but who knows.

**Comment by burodepeper** [comment] 2016-10-31 15:06
You beat me to it! ;) I was busy searching the `autocomplete-plus` documentation for hints. The most important things I've found are that the Symbol provider is experimental (why the hell they made it the default, who knows) and that it isn't intended for plain-text/markdown documents. Maybe having every word indexed for autocompletion is a big performance hit for larger files.

I've looked at creating a SymbolProvider for Markdown, but it doesn't really make sense for an average user. Anyway, I think I'll add a note about your solution in the README, and I suppose that'll have to suffice. Any other ideas?

**Comment by githubnemo** [comment] 2016-10-31 16:33
You could make it opt-in with a config option. I'm not sure if it is possible to modify the selector in the config file dynamically but if it is not, you could dynamically add a `.text.md .completion` tag in case the user activated the completion setting and configure the autocomplete settings to match on '.completion' for constant values.

Manually changing the config file of a third-party package would not be very practical, especially when updating packages.

**Comment by burodepeper** [comment] 2016-10-31 17:19
> Manually changing the config file of a third-party package would not be very practical, especially when updating packages.

I'm afraid this is part of the philosophy of Atom. You're somewhat expected, as a user, to be comfortable with doing stuff like that yourself, often on top of figuring out _how_ to even do it. The thing about the `SymbolProvider` is that it's a static file without a practical way of turning it on or off. The same goes for grammars for instance. I've looked into that extensively; allowing users to specify which variations of Markdown they want supported. I know how to solve it, theoretically, but it would be a shitty user experience for at least 95% of the user base. I'm afraid an opt-in for autocompletion that changes the config settings of a _different package_ and probably creates a custom config file that creates the symbols needed; that sounds like a potential shitload of incoming issues.

For now, at least, I'm taking the road of least resistance: some additional research into how it works (maybe a surprise solution presents itself, who knows) , and then a guide in the README. Anyway, I'm glad the issue is resolved for you, and if you feel up for it, I welcome you to come up and submit a patch to solve this for other users.

**Comment by githubnemo** [comment] 2016-10-31 17:49
> I'm afraid an opt-in for autocompletion that changes the config settings of a different package and probably creates a custom config file that creates the symbols needed; that sounds like a potential shitload of incoming issues.

But it is not for a different package. Only `language-markdown`'s config file needs to be changed for that. And it is only one symbol for text.

> For now, at least, I'm taking the road of least resistance

Fair enough. Thanks for the quick support though.

**Comment by burodepeper** [comment] 2016-10-31 17:54
You're welcome.

> But it is not for a different package. Only language-markdown's config file needs to be changed for that. And it is only one symbol for text.

Yes and no; I believe it's a bit more complicated, but I also just heard my microwave beep, so it's time for some food! I'm keeping this open until I've made up my mind with some thorougher research. I'll update the thread if I have a conclusive opinion.

**Comment by burodepeper** [comment] 2016-12-05 12:06
I've added a reference to this issue in the new [FAQ](https://github.com/burodepeper/language-markdown/blob/master/FAQ.md), so I'm closing this.

**Closed by burodepeper** 2016-12-05 12:06 UTC
