### ISSUE TITLE
Broken code highlighting when using quotation marks

### ISSUE THREAD

**Issue by zrtYouyou** [burodepeper/language-markdown#258] opened 2020-07-17 10:21 UTC
Hi All!

I'm opening a bug report because of the following issue:

When editing a Markdown file, if I insert a code block containing quotation mark after a letter, this is breaking the rest of the coloration until the end of the file.

Here's a quick example of my problem:
![md_coloration_issue](https://user-images.githubusercontent.com/51179979/87774143-71b0a000-c824-11ea-8266-4521f2284465.png)

The quotation mark after the "C" is breaking everything.

If there's no letter, everything is fine.

If there's another letter, problem is the same.

And finally, if I get rid of it, everything works.

Feel free to ask any needed questions.

Here's the used versions :
Linux 5.7.4-arch1-1
Atom    : 1.49.0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0
Language-markdown : 0.37.0

**Comment by burodepeper** [comment] 2020-07-17 12:04
Hi @zrtYouyou,
This is most likely related to #182, and, if dig a little deeper into it, not caused by this issue, but rather by the c(++) package. It's been broken for quite a while, and I'm not up to date on any progress made towards fixing it. I'm afraid I can't help you, so I'm closing this as a duplicate.

**Closed by burodepeper** 2020-07-17 12:04 UTC

**Comment by zrtYouyou** [comment] 2020-07-17 13:28
Ok fine, as the #182 does not talk exactly about this I didn't match it to my current problem... My bad.

Thank you for the quick feedback @burodepeper!

**Comment by burodepeper** [comment] 2020-07-17 13:35
I totally understand. No worries. Perhaps it helps finding a solution elsewhere. Good luck!
