### ISSUE TITLE
Add support for language-babel

### ISSUE THREAD

**Issue by remcohaszing** [burodepeper/language-markdown#211] opened 2018-01-18 13:46 UTC
I use [language-babel](https://atom.io/packages/language-babel) for highlighting my JavaScript files. I think it would be nice if language-markdown would support this.

Since this is a non-standard language, I'm not sure how this should be supported. Perhaps a custom mapping could be made from a code fence language to a source type.

**Comment by burodepeper** [comment] 2018-01-18 22:55
The easiest way to include this would be to add `babel` as a language to code fences, so you'd do: <code>\```babel</code> instead of <code>```js</code>. Wouldn't be supported anywhere outside of Atom though.

**Comment by burodepeper** [comment] 2018-06-15 15:52
I've added language-babel support. Will be part of upcoming release. Once it is available, let me know if it works as intended.

![schermafbeelding 2018-06-15 om 17 50 18](https://user-images.githubusercontent.com/3703530/41477487-c34f6900-70c4-11e8-9a94-c159bac5efe6.png)

**Closed by burodepeper** 2018-06-15 15:52 UTC
