### ISSUE TITLE
Disable ampersand highlighting

### ISSUE THREAD

**Issue by fhchl** [burodepeper/language-markdown#174] opened 2017-03-29 08:35 UTC
Are ampersands not allowed in some Markdown flavors? Why is it highlighted like this?
![ampersands](https://cloud.githubusercontent.com/assets/6132231/24445487/57c08578-146a-11e7-8d31-37ffc1c59ca1.PNG)

**Comment by burodepeper** [comment] 2017-03-29 08:50
Because HTML is allowed inside of Markdown documents, the default language-html package is included in language-markdown. In HTML, the ampersand is considered a special character and as such language-html marks stray ampersands as 'invalid'. This highlighting is not something this package does. I did however add some [specific behavior](https://github.com/burodepeper/language-markdown/blob/master/grammars/repositories/inlines/entities.cson#L5-L9) for an ampersand surrounded by whitespace to not be highlighted, because I feel it is a regular thing to find in texts and I expect a Markdown parser to pick up on it.

**Comment by burodepeper** [comment] 2017-04-04 08:58
There are two possibilities.

1) We could come up with a pattern of how ampersands are normally used in text. `M&M's` looks okay, but `M& M's` is probably a typo, for instance. This solution helps the purpose of a syntax highlighter to show potential errors.

2) You could overwrite the styles for faulty ampersands in your custom stylesheet. The language-html grammar would still detect stray ampersands, but they simply wouldn't have any style associated with them anymore.

The second option is not a real solution, but in this case the easiest, and it would only apply to your situation, so it doesn't change any behavior for other users. Are you familiar enough with CSS to do this yourself?

**Comment by burodepeper** [comment] 2018-10-11 07:56
I think so too. Will verify these changes.

**Comment by burodepeper** [comment] 2018-10-15 12:17
Closing. Seems fixed. Added some tests in 13a15f9 to avoid/detect regressions.

**Closed by burodepeper** 2018-10-15 12:17 UTC
