### ISSUE TITLE
Markdown Preview not triggered within text.md scope

### ISSUE THREAD

**Issue by edent** [burodepeper/language-markdown#51] opened 2015-11-26 20:30 UTC
Ok... This is a bit weird. My first time using atom - so let me know if it's something I'm doing wrong.

I've installed the `language-markdown` package - now I can't open the preview pane.  

`ctrl+shift+m` doesn't work, neither does `Packages->Markdown Preview->Toggle Preview`.

If I switch the document formatting to "GitHub Markdown", I *can* turn on the preview. If I switch back to markdown, the preview pane stays there and, seemingly, works.

The only other package I've installed is [markdown-scroll-sync](https://atom.io/packages/markdown-scroll-sync)

**Comment by burodepeper** [comment] 2015-11-27 10:13
Thanks for reporting. I've been able to reproduce it, so I've got something to work with.
If you right click on the Markdown file in the treeview on the left, does the `Markdown Preview` option show up for you, and if so, does it work?

**Comment by burodepeper** [comment] 2015-11-27 10:18
Ah, figured it out already : )

If you open the Settings for `markdown-preview` there's an option where you can specify within which grammars the previewing should be enabled. The default that `language-markdown` uses, `text.md` is not in there. So if you change that to `source.gfm, source.litcoffee, text.html.basic, text.plain, text.md` it will work with this package as well.

I'll ask them to add `text.md` to the defaults, or see if I can do that myself in some way.

**Comment by burodepeper** [comment] 2015-11-27 11:33
@edent I've created a PR over at `markdown-preview` so let's hope it will be part of their next update. See: https://github.com/atom/markdown-preview/pull/344

**Comment by burodepeper** [comment] 2015-12-01 07:46
Hi @edent, my PR is merged into markdown-preview, so with a bit of luck it will be part of the next Atom update. I'll leave this issue open until I can verify that it is fixed.

**Comment by burodepeper** [comment] 2016-01-10 10:46
Did a double check, and the updated `markdown-preview` won't be included until Atom 1.5 if I'm correct. Bummer.
/cc @KaiBueker

**Comment by Arcanemagus** [comment] 2016-01-10 21:23
It's in v1.4.0-beta3... unless they plan on removing it?

**Comment by burodepeper** [comment] 2016-01-10 21:24
Oh I didn't check v1.4, but that's nothing but good news! Thanks for checking.

**Comment by Arcanemagus** [comment] 2016-01-10 21:26
I was quite happy when I was able to enable this language and still use the preview, would be amazing if this replaced the one built into Atom (or if they just you know... fixed the bugs in it...).

So tired of having users report bugs on the linter plugins that they are linting markdown files when they shouldn't be, but at least I have your package to point them to :wink:.

**Comment by burodepeper** [comment] 2016-01-11 09:05
Perhaps I should tell them `language-markdown` exists, and that they only need change their `package.json` to include it? I suppose a PR to swap out `language-gfm` would be considered a little rude... ; )

**Comment by burodepeper** [comment] 2016-01-14 16:37
Closing this because 1.4 is released!

**Closed by burodepeper** 2016-01-14 16:37 UTC
Labels: needs verification
